# Netlify CMS Configuration File

# The backend option specifies how to access the content for your site
backend:
  # Git Updates
  name: git-gateway

  # The branch to update (optional; defaults to master)
  # Update this branch (but do not commit) as needed, when working locally
  branch: main

# Uncomment to Test/Edit local content
# local_backend: true

# Uncomment below to enable drafts https://www.netlifycms.org/docs/add-to-your-site/#editorial-workflow
# publish_mode: editorial_workflow

# Uncomment below to enable a link to your published site in the header bar of Netlify CMS
# site_url: https://eleventy-netlify-boilerplate.netlify.app/

media_folder: "src/site/_includes/assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "_site/assets/uploads"

collections:
  # Blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src/site/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "src/site/pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  # Showcase content
  - name: "showcase"
    label: "Showcase"
    folder: "src/site/showcase"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Event Date", name: "event_date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Teaser Image", name: "teaser", widget: "file" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - {
          label: "Category",
          name: "category",
          widget: "list",
          required: true,
          field: { label: "Category Term", name: "category_term", widget: "relation", collection: "category", searchFields: ['title'], valueField: ["title", "teaser_image", "description" ] }
        }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: ["post"] }
      - { label: "External URL", name: "external_url", widget: "string", "hint": "Add an external link to the resource, as needed." }
      - label: "Testimonials"
        name: "testimonials"
        collapsed: false
        widget: "list"
        fields:
          - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
          - {label: Author, name: author, widget: string }
      - label: "Page Builder"
        name: "page_builder"
        widget: "list"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Video Embed", name: "video_embed", widget: "markdown" }
  # Taxonomy: Category
  - name: "category"
    label: "Taxonomy: Category"
    folder: "src/site/category"
    create: true # Allow users to create new documents in this collection
    slug: "taxonomy/category/{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Teaser Image", name: "teaser_image", widget: "file" }
      - { label: "Description", name: "description", widget: "markdown" }
